const allProducts = [
  {
    id: 'pudina-capsules',
    badge: 'save 27%',
    name: 'Pudina Capsules',
    rating: 5,
    price: 399,
    originalPrice: 549,
    category: 'Digestive Care',
    image: '/images/products/pudina-capsules.png',
    summary: 'Digestive and cooling support for everyday gut comfort.',
    benefits: [
      'Relieves indigestion and acidity',
      'Helps reduce bloating after meals',
      'Supports fresh breath and lightness',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'mulethi-powder',
    badge: 'save 30%',
    name: 'Mulethi Powder',
    rating: 4,
    price: 349,
    originalPrice: 499,
    category: 'Respiratory Care',
    image: '/images/products/mulethi-powder.png',
    summary: 'Soothing throat and respiratory support in a daily powder.',
    benefits: [
      'Soothes cough and sore throat',
      'Helps respiratory comfort',
      'Useful in seasonal wellness routines',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'haritaki-powder',
    badge: 'save 28%',
    name: 'Haritaki Powder',
    rating: 4,
    price: 359,
    originalPrice: 499,
    category: 'Digestive Care',
    image: '/images/products/haritaki-powder.png',
    summary: 'Colon cleanser and detox support for balanced digestion.',
    benefits: [
      'Supports digestion and regularity',
      'Helps natural detox routines',
      'Useful for gut wellness support',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'amla-powder',
    badge: 'save 31%',
    name: 'Amla Powder',
    rating: 5,
    price: 379,
    originalPrice: 549,
    category: 'Immunity Care',
    image: '/images/products/amla-powder.png',
    summary: 'Vitamin-rich amla support for immunity, hair and skin health.',
    benefits: [
      'Boosts immunity naturally',
      'Supports hair and skin glow',
      'Powerful antioxidant support',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'shilajit-capsules',
    badge: 'save 31%',
    name: 'Shilajit Capsules',
    rating: 5,
    price: 899,
    originalPrice: 1299,
    category: "Men's Health",
    image: '/images/products/shilajit-capsules.png',
    summary: 'Energy and stamina support with a focused daily capsule format.',
    benefits: [
      'Boosts energy and stamina',
      'Supports strength and performance',
      'Helps improve vitality',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'triphala-powder',
    badge: 'save 31%',
    name: 'Triphala Powder',
    rating: 4,
    price: 329,
    originalPrice: 479,
    category: 'Digestive Care',
    image: '/images/products/triphala-powder.png',
    summary: 'Digestive health support with the classic triphala blend.',
    benefits: [
      'Improves digestion gently',
      'Supports natural detox',
      'Good for daily gut balance',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'neem-capsules',
    badge: 'save 28%',
    name: 'Neem Capsules',
    rating: 4,
    price: 429,
    originalPrice: 599,
    category: 'Skin Care',
    image: '/images/products/neem-capsules.png',
    summary: 'Blood and skin wellness support with neem-based capsules.',
    benefits: [
      'Purifies blood support',
      'Helps healthy skin routines',
      'Supports immunity and cleansing',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'giloy-capsules',
    badge: 'save 30%',
    name: 'Giloy Capsules',
    rating: 5,
    price: 449,
    originalPrice: 649,
    category: 'Immunity Care',
    image: '/images/products/giloy-capsules.png',
    summary: 'Immunity and wellness support in an easy daily capsule.',
    benefits: [
      'Enhances immunity naturally',
      'Supports anti-fatigue wellness',
      'Good for year-round vitality',
    ],
    tags: ['Pickup', 'Delivery'],
  },
  {
    id: 'safed-musli-capsules',
    badge: 'save 33%',
    name: 'Safed Musli Capsules',
    rating: 5,
    price: 999,
    originalPrice: 1499,
    category: 'Vitality Care',
    image: '/images/products/safed-musli-capsules.png',
    summary: 'Strength and vitality support with a premium daily capsule.',
    benefits: [
      'Supports strength and stamina',
      'Useful for reproductive wellness',
      'Helps daily energy balance',
    ],
    tags: ['Pickup', 'Delivery'],
  },
]

const stories = [
  {
    id: 'rajat',
    stars: 5,
    quote:
      "My fiance and I had plans for valentine's that went refreshingly great after consuming these capsules.",
    author: 'Rajat',
  },
  {
    id: 'rupesh',
    stars: 5,
    quote:
      'Very effective. I felt energized after consuming it for 3-4 days only. ST Herbal always stands true to its quality.',
    author: 'Rupesh',
  },
  {
    id: 'ankur',
    stars: 5,
    quote:
      'After using this shilajit range, I do not feel lethargic even after long work hours and I saw steady improvement.',
    author: 'Ankur Tanwar',
  },
  {
    id: 'rajnish',
    stars: 5,
    quote:
      'I could see a decent performance increase. Would surely recommend it.',
    author: 'Rajnish',
  },
]

export const homepageData = {
  promoBar: {
    note: 'For expert consultation talk to the expert instantly',
    phone: '+91 8860060078',
    highlight: 'Over 100k happy customers',
  },
  header: {
    brand: 'ST Herbal Care',
    categoriesLabel: 'Categories',
    searchPlaceholder: 'What are you looking for ?',
    primaryLinks: ['Home', 'Shop', 'About Us', 'Contact'],
    shortcuts: [
      { id: 'track-orders', label: 'Track your orders', icon: 'truck' },
      { id: 'account', label: 'Account', icon: 'user' },
      { id: 'cart', label: 'Cart', icon: 'bag' },
    ],
    infoPills: [
      { id: 'hot-deals', label: 'Hot Deals', icon: 'spark' },
      { id: 'support', label: 'Call support: (+91)8860060078', icon: 'phone' },
    ],
  },
  hero: {
    title: 'Ashwagandha',
    subtitle: 'For Stress & Immunity',
  },
  categories: [
    {
      id: 'digestive',
      title: 'Digestive Care',
      subtitle: 'Gut balance',
      icon: 'pulse',
      tone: 'mint',
    },
    {
      id: 'men-health',
      title: "Men's Health",
      subtitle: 'Strength support',
      icon: 'strength',
      tone: 'sand',
    },
    {
      id: 'immunity',
      title: 'Immunity Care',
      subtitle: 'Daily defence',
      icon: 'glow',
      tone: 'peach',
    },
    {
      id: 'respiratory',
      title: 'Respiratory Care',
      subtitle: 'Throat comfort',
      icon: 'hair',
      tone: 'cloud',
    },
    {
      id: 'skin-care',
      title: 'Skin Care',
      subtitle: 'Natural radiance',
      icon: 'skin',
      tone: 'rose',
    },
    {
      id: 'vitality',
      title: 'Vitality Care',
      subtitle: 'Wellness strength',
      icon: 'balance',
      tone: 'sage',
    },
  ],
  serviceBanner: {
    title: 'Delivery at your door step',
    subtitle: 'We are available for every time.',
    seal: '6 days delivery promise',
    ctaLabel: 'Order Now',
  },
  sections: [
    {
      id: 'top-sellers',
      title: 'Shop our top sellers',
      accent: 'blue',
      products: [
        allProducts[0],
        allProducts[4],
        allProducts[7],
        allProducts[8],
        allProducts[6],
      ],
    },
    {
      id: 'deals',
      title: 'Deals of the day',
      accent: 'green',
      countdown: ['00', '00', '00', '00'],
      products: [
        allProducts[1],
        allProducts[3],
        allProducts[5],
        allProducts[2],
        allProducts[0],
      ],
    },
    {
      id: 'recommended',
      title: 'Recommended for you',
      accent: 'blue',
      products: [
        allProducts[7],
        allProducts[6],
        allProducts[3],
        allProducts[4],
        allProducts[8],
      ],
    },
  ],
  shop: {
    banner: {
      eyebrow: 'buy more, save more',
      title: 'Shop Herbal Care',
      description:
        'Explore every capsule and powder from ST Herbal Care in one linked shop page with real product images.',
      ctaLabel: 'Browse All',
      image: '/images/hero-banner.png',
    },
    products: allProducts,
  },
  roots: {
    title: 'Our Roots',
    description:
      'ST Herbal Care focuses on close-to-nature herbal formulas with a trust-first shopping experience, clear product benefits and easy navigation from homepage to shop.',
    ctaLabel: 'Know More',
    pillars: [
      { id: 'gmp', label: 'GMP, ISO & Non-GMO', icon: 'certified' },
      { id: 'natural', label: 'Natural & Safe', icon: 'leaf' },
      { id: 'side-effects', label: 'No Side Effects', icon: 'ban' },
      { id: 'metals', label: 'Pure, No Heavy Metals', icon: 'shield' },
    ],
  },
  testimonials: {
    title: 'Real people, real stories',
    entries: stories,
  },
  trustBadges: [
    {
      id: 'free-delivery',
      title: 'Free Delivery',
      description: 'Free delivery for orders above Rs500',
      icon: 'delivery',
    },
    {
      id: 'pricing',
      title: 'Everyday Low Price',
      description: 'Collection at the lowest price',
      icon: 'wallet',
    },
    {
      id: 'returns',
      title: 'Satisfied or Refunded',
      description: 'Guaranteed product quality',
      icon: 'refresh',
    },
    {
      id: 'payments',
      title: 'Secure Payments',
      description: 'Safety payment technologies',
      icon: 'lock',
    },
  ],
  footer: {
    newsletterTitle: 'send me up-to-date information',
    newsletterPlaceholder: 'Email address',
    newsletterCta: 'Subscribe',
    customerLinks: ['My Account', 'Track My Order', 'Return Policy', 'Wishlist'],
    quickLinks: [
      'Privacy Policy',
      'Terms and Condition',
      'Shipping Policy',
      'Cancellation Policy',
      'Contact Us',
    ],
    addressLabel: 'store location',
    address:
      'Shop No-1, Property No. 541, New Gran Market, Karnal - 132001, Haryana',
    phoneLabel: 'customer support',
    phone: '8860060078',
    payments: ['visa', 'mastercard', 'rupay', 'paypal'],
    copyright: 'Copyright (c) 2025 stherbalcare. All rights reserved',
  },
}

export default homepageData
